# wrong solution


# this solution passes when n <= 3, but fails when n > 3. 

# i thought when f() is the current well-formed parentheses string, we can generate new well-formed parentheses strings by:
# 1. '(' + f() + ')'
# 2. '()' + f()
# 3. f() + '()'

# however, this is incorrect. counter example (n == 4): "(())(())" cannot be generated by the above three operations.


class Solution:
    def generateParenthesis(self, n: int) -> List[str]:
        ans = set()
        def gen(curr, n):
            nonlocal ans

            if n == 0:
                if curr not in ans:
                    ans.add(curr)
                return
            
            gen('(' + curr + ')', n-1)
            gen('()' + curr, n-1)
            gen(curr + '()', n-1)


        gen('', n)

        return list(ans)


# notes while solving:
# f()f()f()

# f(f(f()))

# f(f()f())

