# submission: https://leetcode.com/problems/asteroid-collision/submissions/2043420306/
# runtime: 8 ms (beats 26.36%), memory: 20.65 MB (beats 7.84%)
# 26 min
# solved using stack

# TC: O(n)
# SC: O(n) (stack)


# my thought process is as follows:
# 1. considering the input length, assumed the solution should be at most O(n log n) time complexity; then since it seems i don't need to use sorting, binary search, or etc. that requires O(n log n) or O(log n) time, directly considered algorithm that requires O(n) time.
# 2. tried to find out when the collision occurs, and noticed that the collision occurs when one element is moving to the left, and the previous one (or the one on the left side) is moving to the right.
# 3. tried simulating one element at a time just like iterating through the input array; spotted that i need to check if the current asteroid is going to collide with the previous one when the current asteroid is moving to the left. at this moment, i ensured this is a stack problem.
# 4. since the current asteroid could collide with not only the adjacent previous one but also all of the previous ones, i needed to keep checking the previous ones (can be easily implemented with a `while` loop) until there are no more collisions.

# cf.) the code below is a little verbose. more concise and readable code generated by ChatGPT can be found here:
# https://leetcode.com/problems/asteroid-collision/submissions/2043685024/—runtime: 7 ms (beats 58.23%), memory: 20.52 MB (beats 7.84%)


from collections import deque


class Solution:
    def asteroidCollision(self, asteroids: List[int]) -> List[int]:
        n = len(asteroids)
        stack = deque([asteroids[0]])

        for i in range(1, n):
            if asteroids[i] > 0:
                stack.append(asteroids[i])
            else:
                is_same_size = False
                while stack and stack[-1] > 0:
                    if stack[-1] < -asteroids[i]:
                        stack.pop()
                    elif stack[-1] == -asteroids[i]:
                        stack.pop()
                        is_same_size = True
                        break
                    else:
                        break
                    
                # negation on `is_same_size or (stack and stack[-1] > 0)`
                if not is_same_size and (not stack or stack[-1] < 0):
                    stack.append(asteroids[i])
                
        return list(stack)
